# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: digitaltech.id
          username: root
          key: ${{ secrets.PRIVATE_KEY }}
          port: 2232
          script: |
            cd /var/www/formISP
            git pull origin master
            git status
            php artisan config:clear
            systemctl restart nginx
